### ISSUE TITLE
Side Bar Shortcut

### ISSUE THREAD

**Issue by daven1985** [evnix/codowik#9]
Morning,

I just started using Codowik on my dokuwiki and love it. Though one thing bugs me to high heaven... is there a way to disable the Ctrl+Arrow that autohides the side bar. I use that (with shift) to highlight words when typing but this just closes and opens the sidebar, which I am happy to leave always on.

Thanks.

**Comment by sandebert** [comment]
Did you find where one disable this shortcut? It's driving me crazy.

**Comment by sandebert** [comment]
I found it, there's an option _enableCursorHotkey_ that needs to be set to _false_. There might be some more elegant way of doing this, but at this point I'm so frustrated that I don't care. 

https://github.com/evnix/codowik/blob/master/js/layout.js#L779
